#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE[0]}")"
ROOT_PATH="../../.."

PROJECT_URL=$1
PROJECT_ID=$2
LAST_TAG_JOB_ID=$3
CURRENT_VERSION=$4
GITLAB_REF_PAYLOAD=$(./retrieve_gitlab_reference_info.sh $PROJECT_URL $PROJECT_ID $CURRENT_VERSION)
GIT_SHA_REFERENCE=$(jq .id <<< ${GITLAB_REF_PAYLOAD} | tr -d "\"")

TEMPLATE_PKGBUILD_PATH="./template/template.PKGBUILD"
PKGBUILD_FOLDER_PATH="$ROOT_PATH/PKGBUILD"
NEW_PKGBUILD_PLACE="$PKGBUILD_FOLDER_PATH/ligo@$CURRENT_VERSION.PKGBUILD"
LATEST_PKGBUILD_PLACE="$PKBUILD_FOLDER_PATH/ligo.PKGBUILD"

# Place the template to the good place
cp $TEMPLATE_PKGBUILD_PATH $NEW_PKGBUILD_PLACE

# Fill the template which has been placed
./fill_template.sh $NEW_PKGBUILD_PLACE $LAST_TAG_JOB_ID $CURRENT_VERSION $GIT_SHA_REFERENCE

cp $NEW_PKGBUILD_PLACE $LATEST_PKGBUILD_PLACE

./remove_deprecated_pkgbuild.sh $HOMEBREW_PKGBUILD_FOLDER_PATH $CURRENT_VERSION
