format:
	ocamlformat --profile=default --field-space=tight-decl --break-cases=toplevel --module-item-spacing=preserve --cases-exp-indent=2 --no-space-around-arrays --no-space-around-lists --no-space-around-records --no-space-around-variants *.ml --inplace

