esy-windows:
  tags:
    - windows
  stage: build
  needs: []
  variables:
    GIT_STRATEGY: clone
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev" && $CI_PROJECT_PATH == "ligolang/ligo"'
      when: always
    - if: '$CI_COMMIT_TAG =~ /[0-9]+\.[0-9]+\.[0-9]/ && $CI_PROJECT_PATH == "ligolang/ligo"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PROJECT_PATH == "ligolang/ligo"'
      when: always
  script:
    # - git submodule update --init --recursive
    # - git config http.postBuffer 1048576000
    # - $env:PATH = 'C:\Program Files (x86)\NSIS;C:\Program Files\Git\bin;C:\Users\gitlabrunner\AppData\Roaming\npm;' + $env:PATH
    # - $env:HOME = 'C:/Users/gitlabrunner'
    # - $env:ESY__PREFIX = $env:HOME + '/.esy-nairobi'
    # - git submodule foreach --recursive git reset --hard; git submodule update --init --recursive # ensure previously applied patch is removed
    # - bash -c "patch -p1 < 001-tezos-deps-via-esy.patch"
    # - esy i
    # - bash -c "patch -p1 -R < 001-tezos-deps-via-esy.patch" # So that dune runtest doesn't run tezos tests
    # - bash -c "esy b dune runtest || esy b dune runtest || esy b dune runtest"
    # - bash -c "patch -p1 < 001-tezos-deps-via-esy.patch"
    # - bash -c "esy b --install || esy b --install || esy b --install"
    # - cp ./_build/install/default/bin/ligo.exe ./windows-installer
    # - cp ./LICENSE.md ./windows-installer
    # - cp ./tools/webide-new/ligo-webide-frontend/ligo-ide/public/favicon.ico ./windows-installer
    # - cd windows-installer; makensis .\WindowsInstaller.nsi; mv ligo_installer.exe ../ligo_installer.exe ; cd ..
    - $env:TEST_CERTIFICATE_PASSWORD = "foo"
    - ./scripts/signInstallerWithTestCertificates.ps1
    # - bash -c "esy release || esy release || esy release"
    # - git submodule foreach --recursive git reset --hard; git submodule update --init --recursive # ensure previously applied patch is removed
    # - mv _release platform-windows-x64
  artifacts:
    paths:
      - platform-windows-x64
      - ligo_installer.exe 

