variables:
  LIGO_REGISTRY_IMAGE_BASE_NAME: "${CI_PROJECT_PATH}/${CI_PROJECT_NAME}"
  LIGO_IMAGE_TAG: "ligo:${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"
  LIGO_CI_IMAGE_TAG: "ligo-ci:${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"

stages:
  - pretooling                      # changelog
  - build                           # build, test, produces binaries/.deb/doc within docker
  - post-build-action               # Post build action
  - docker-extract                  # extract what have been built and expose them as artifact
  - tools-precheck                  # preliminary checks done for projects from 'tools'
  - tools-build                     # build projects from 'tools'
  - tools-check                     # run tests for projects from 'tools'
  - tooling                         # build miscellaneous tooling-related things (website, changelog..)
  - test                            # e2e tests
  - push                            # deploy docker images, pages, releases (tag)
  - deploy                          # deploy web IDE, website preview
  - release                         # Manage branch matching ^release/*

include:
  # Manage NPM build
  - '/.ci/.gitlab-ci-npm.yml'

.submodule-clone:
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive --remote
