---
esy-windows:
  tags:
    - windows
  script:
    - $env:TEST_CERTIFICATE_PASSWORD = "foo"
    - ./scripts/signInstallerWithTestCertificates.ps1 -Path ./tmp/camlprog.exe
  artifacts:
    paths:
      - ./tmp
