name:                ligo-webide-backend

dependencies:
- base-noprelude >= 4.9 && < 5
- loot-prelude

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - QuantifiedConstraints
  - QuasiQuotes
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Wno-partial-fields
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - async
  - attoparsec
  - bytestring
  - containers
  - directory
  - exceptions
  - filepath
  - fmt
  - github
  - katip
  - lens
  - lsp-types
  - megaparsec
  - microlens-platform
  - monad-control
  - morley
  - morley-client
  - mtl
  - optparse-applicative
  - process
  - servant-client
  - servant-server
  - servant-swagger-ui
  - servant-openapi3
  - openapi3
  - temporary
  - text
  - transformers
  - unliftio
  - wai
  - wai-cors
  - wai-extra
  - warp
  - websockets

executables:
  ligo-webide-backend:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - katip
    - ligo-webide-backend
    - wai-websockets
    - warp
    - websockets

  swagger-gen:
    main: Main.hs
    source-dirs: scripts/swagger-gen
    dependencies:
      - aeson
      - ligo-webide-backend

tests:
  ligo-webide-backend-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - filepath
    - ligo-webide-backend
    - req
    - tasty
    - tasty-hunit
    - text
    - warp
