# We abort pipeline if the MR last commit of MR is pushed by human and not by bot.
.export-mr-info: &export-mr-info
    - MR_INFO='$(./.ci/scripts/retrieve_merge_request_info.sh ${CI_PROJECT_URL} ${CI_PROJECT_ID} ${CI_MERGE_REQUEST_IID} ${TOKEN_API})'
    - export MR_AUTHOR_USERNAME=$(nix-shell -p jq --run "jq \".author.username\" <<< ${MR_INFO}")
    - export MR_TITLE=$(nix-shell -p jq --run "jq \".title\" <<< ${MR_INFO}")
    - MR_RAW_DESCRIPTION=$(nix-shell -p jq --run "jq \".description\" <<< ${MR_INFO}")
    - export MR_TYPE=$(sed  -e 's/.*type:\(breaking\|added\|fixed\|changed\|deprecated\|removed\|performance\|internal\|other\|none\).*/\L\1/I' <<< $MR_RAW_DESCRIPTION)
    - MD_DESC_SEPARATOR="Changelog details:\n"
    - export MR_DESC=$(sed -e 's/.*Changelog details:\\n\(.*\)/\1/' <<< $MR_RAW_DESCRIPTION)
    
add-changelog-entry:
  stage: pretooling
  extends : .nix
  before_script:
    - *export-mr-info
  script:
  # Check if type is None, if None, skip changelog geeration
    - git remote rm origin && git remote add origin "git@gitlab.com:ligolang/ligo.git" 
    - ./scripts/add-changelog-entry.sh "$MR_TYPE" "$CI_MERGE_REQUEST_IID" "$MR_AUTHOR_USERNAME" "$MR_TITLE" "$MR_DESC"
    - git add changelog/*
    - git commit -m "[Bot] add changelog entry"
    - git push origin HEAD:$CI_COMMIT_REF_NAME
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
      changes:
          - changelog/*
      when: never
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/)
      when: always

abort-MR-without-changelog:
  stage: pretooling
  extends : .nix
  before_script:
    - *export-mr-info
  script:
    - echo "This pipeline will be aborted. A bot should have push a new changelog entry which will trigger the pipeline.
      If you don't want changelog entry, use type 'none' in your MR. If you want to manage it manually, add a changelog entry
      into changelog folder (with script add-changelog-entry.sh or not)."
    - ([[ $MR_TYPE = none ]] && exit 1)
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event")
      changes:
          - changelog/*
      when: never
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/)
