[build]
  publish = "build"

## This section is for the Netlify redirect. The hostname below points to the alternative server
[[redirects]]
  from = "/api/*"
  to = "https://ligo-web-ide-prod.gcp.marigold.prod/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/p/*"
  to = "/index.html"
  status = 200
  force = true