[build]
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://ligo-web-ide-dev.gcp-npr.marigold.dev/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/p/*"
  to = "/index.html"
  status = 200
  force = true
