name: ligo-debugger

dependencies:
  - base-noprelude
  - morley-prelude

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumDecimals
  - OverloadedStrings
  - PackageImports
  - QuantifiedConstraints
  - QuasiQuotes
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Weverything
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Wno-partial-fields
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unused-packages

library:
  dependencies:
    - aeson
    - ansi-terminal
    - attoparsec
    - bytestring
    - conduit
    - conduit-extra
    - containers
    - data-default
    - dlist
    - duplo
    - fastsum
    - filepath
    - fmt
    - free
    - hashable
    - lens
    - monad-stm
    - morley
    - morley-debugger
    - mtl
    - nyan-interpolation
    - nyan-interpolation-core
    - process
    - process-extras
    - regex-tdfa
    - scientific
    - semver
    - singletons
    - singletons-th
    - stm
    - stm-containers
    - syb
    - template-haskell
    - th-utilities
    - time
    - text
    - transformers
    - tree-sitter
    - unliftio
    - unliftio-core
    - unordered-containers
    - vector
    - vinyl
    - witherable

  source-dirs:
    - src/

  include-dirs:
    - grammar/camligo/src
    - grammar/jsligo/src

  c-sources:
    - grammar/camligo/src/parser.c
    - grammar/camligo/src/scanner.c
    - grammar/jsligo/src/parser.c
    - grammar/jsligo/src/scanner.c

  generated-other-modules:
    - Paths_ligo_debugger

executables:
  ligo-debugger:
    main: Main.hs

    dependencies:
      - ligo-debugger
      - morley
      - morley-debugger
      - semver

    source-dirs:
      - app/ligo-debugger

    generated-other-modules:
      - Paths_ligo_debugger

    ghc-options:
      - -threaded
      - -eventlog
      - -rtsopts
      - '"-with-rtsopts=-N -A64m -AL256m"'

tests:
  ligo-debugger-test:
    main: Main.hs

    dependencies:
      - containers
      - data-default
      - Diff
      - directory
      - duplo
      - filepath
      - fmt
      - hedgehog
      - hspec-expectations
      - lens
      - ligo-debugger
      - lorentz
      - nyan-interpolation
      - nyan-interpolation-core
      - morley
      - morley-debugger
      - mtl
      - singletons
      - tasty
      - tasty-golden
      - text
      - unliftio
      - unordered-containers
      - HUnit
      - tasty-hedgehog
      - tasty-hunit-compat

    source-dirs:
      - test

    ghc-options:
      - -threaded
      - -eventlog
      - -rtsopts
      - '"-with-rtsopts=-N -A64m -AL256m"'

    build-tools: tasty-discover:tasty-discover
