open Stage_common.Enums

let constant'_tag = function
  | C_INT                     ->   [%incr]
  | C_UNIT                    ->   [%incr]
  | C_NIL                     ->   [%incr]
  | C_NOW                     ->   [%incr]
  | C_IS_NAT                  ->   [%incr]
  | C_SOME                    ->   [%incr]
  | C_NONE                    ->   [%incr]
  | C_ASSERTION               ->   [%incr]
  | C_ASSERT_INFERRED         ->   [%incr]
  | C_ASSERT_SOME             ->   [%incr]
  | C_FAILWITH                ->   [%incr]
  | C_UPDATE                  ->   [%incr]
  (* Loops *)
  | C_ITER                    ->  [%incr]
  | C_FOLD_WHILE              ->  [%incr]
  | C_FOLD_CONTINUE           ->  [%incr]
  | C_FOLD_STOP               ->  [%incr]
  | C_LOOP_LEFT               ->  [%incr]
  | C_LOOP_CONTINUE           ->  [%incr]
  | C_LOOP_STOP               ->  [%incr]
  | C_FOLD                    ->  [%incr]
  | C_FOLD_LEFT               ->  [%incr]
  | C_FOLD_RIGHT              ->  [%incr]
  (* MATH *)
  | C_NEG                     ->  [%incr]
  | C_ABS                     ->  [%incr]
  | C_ADD                     ->  [%incr]
  | C_SUB                     ->  [%incr]
  | C_MUL                     ->  [%incr]
  | C_EDIV                    ->  [%incr]
  | C_DIV                     ->  [%incr]
  | C_MOD                     ->  [%incr]
  (* LOGIC *)
  | C_NOT                     ->  [%incr]
  | C_AND                     ->  [%incr]
  | C_OR                      ->  [%incr]
  | C_XOR                     ->  [%incr]
  | C_LSL                     ->  [%incr]
  | C_LSR                     ->  [%incr]
  (* COMPARATOR *)
  | C_EQ                      ->  [%incr]
  | C_NEQ                     ->  [%incr]
  | C_LT                      ->  [%incr]
  | C_GT                      ->  [%incr]
  | C_LE                      ->  [%incr]
  | C_GE                      ->  [%incr]
  (* Bytes/ String *)
  | C_SIZE                    ->  [%incr]
  | C_CONCAT                  ->  [%incr]
  | C_SLICE                   ->  [%incr]
  | C_BYTES_PACK              ->  [%incr]
  | C_BYTES_UNPACK            ->  [%incr]
  | C_CONS                    ->  [%incr]
  (* Pair *)
  | C_PAIR                    ->  [%incr]
  | C_CAR                     ->  [%incr]
  | C_CDR                     ->  [%incr]
  | C_LEFT                    ->  [%incr]
  | C_RIGHT                   ->  [%incr]
  (* Set *)
  | C_SET_EMPTY               ->  [%incr]
  | C_SET_LITERAL             ->  [%incr]
  | C_SET_ADD                 ->  [%incr]
  | C_SET_REMOVE              ->  [%incr]
  | C_SET_UPDATE              ->  [%incr]
  | C_SET_ITER                ->  [%incr]
  | C_SET_FOLD                ->  [%incr]
  | C_SET_FOLD_DESC           ->  [%incr]
  | C_SET_MEM                 ->  [%incr]
  (* List *)
  | C_LIST_EMPTY              ->  [%incr]
  | C_LIST_LITERAL            ->  [%incr]
  | C_LIST_ITER               ->  [%incr]
  | C_LIST_MAP                ->  [%incr]
  | C_LIST_FOLD               ->  [%incr]
  | C_LIST_FOLD_LEFT          ->  [%incr]
  | C_LIST_FOLD_RIGHT         ->  [%incr]
  | C_LIST_HEAD_OPT           ->  [%incr]
  | C_LIST_TAIL_OPT           ->  [%incr]
  (* Maps *)
  | C_MAP                     ->  [%incr]
  | C_MAP_EMPTY               ->  [%incr]
  | C_MAP_LITERAL             ->  [%incr]
  | C_MAP_GET                 ->  [%incr]
  | C_MAP_GET_FORCE           ->  [%incr]
  | C_MAP_ADD                 ->  [%incr]
  | C_MAP_REMOVE              ->  [%incr]
  | C_MAP_UPDATE              ->  [%incr]
  | C_MAP_ITER                ->  [%incr]
  | C_MAP_MAP                 ->  [%incr]
  | C_MAP_FOLD                ->  [%incr]
  | C_MAP_MEM                 ->  [%incr]
  | C_MAP_FIND                ->  [%incr]
  | C_MAP_FIND_OPT            ->  [%incr]
  (* Big Maps *)
  | C_BIG_MAP                 ->  [%incr]
  | C_BIG_MAP_EMPTY           ->  [%incr]
  | C_BIG_MAP_LITERAL         ->  [%incr]
  (* Crypto *)
  | C_SHA256                  ->  [%incr]
  | C_SHA512                  ->  [%incr]
  | C_BLAKE2b                 ->  [%incr]
  | C_HASH                    ->  [%incr]
  | C_HASH_KEY                ->  [%incr]
  | C_CHECK_SIGNATURE         ->  [%incr]
  | C_CHAIN_ID                ->  [%incr]
  (* Blockchain *)
  | C_CALL                    ->  [%incr]
  | C_CONTRACT                ->  [%incr]
  | C_CONTRACT_OPT            ->  [%incr]
  | C_CONTRACT_ENTRYPOINT     ->  [%incr]
  | C_CONTRACT_ENTRYPOINT_OPT -> [%incr]
  | C_AMOUNT                  -> [%incr]
  | C_BALANCE                 -> [%incr]
  | C_SOURCE                  -> [%incr]
  | C_SENDER                  -> [%incr]
  | C_ADDRESS                 -> [%incr]
  | C_SELF                    -> [%incr]
  | C_SELF_ADDRESS            -> [%incr]
  | C_IMPLICIT_ACCOUNT        -> [%incr]
  | C_SET_DELEGATE            -> [%incr]
  | C_CREATE_CONTRACT         -> [%incr]
  | C_TRUE                    -> [%incr]
  | C_FALSE                   -> [%incr]
  | C_TEST_ORIGINATE          -> [%incr]
  | C_TEST_SET_NOW            -> [%incr]
  | C_TEST_SET_SOURCE         -> [%incr]
  | C_TEST_SET_BAKER          -> [%incr]
  | C_TEST_EXTERNAL_CALL_TO_CONTRACT -> [%incr]
  | C_TEST_GET_STORAGE        -> [%incr]
  | C_TEST_GET_BALANCE        -> [%incr]
  | C_TEST_MICHELSON_EQUAL    -> [%incr]
  | C_TEST_LOG                -> [%incr]
  | C_SHA3                    -> [%incr]
  | C_KECCAK                  -> [%incr]
  | C_LEVEL                   -> [%incr]
  | C_VOTING_POWER            -> [%incr]
  | C_TOTAL_VOTING_POWER      -> [%incr]
  | C_TICKET                  -> [%incr]
  | C_READ_TICKET             -> [%incr]
  | C_SPLIT_TICKET            -> [%incr]
  | C_JOIN_TICKET             -> [%incr]
  | C_PAIRING_CHECK           -> [%incr]
  | C_MAP_GET_AND_UPDATE      -> [%incr]
  | C_BIG_MAP_GET_AND_UPDATE  -> [%incr]
  | C_SAPLING_EMPTY_STATE     -> [%incr]
  | C_SAPLING_VERIFY_UPDATE   -> [%incr]
  | C_TEST_STATE_RESET        -> [%incr]
  | C_TEST_EXTERNAL_CALL_TO_CONTRACT_EXN  -> [%incr]
  | C_TEST_GET_NTH_BS         -> [%incr]
  | C_TEST_LAST_ORIGINATIONS  -> [%incr]
  | C_TEST_COMPILE_META_VALUE -> [%incr]
  | C_TEST_RUN                -> [%incr]
  | C_TEST_EVAL               -> [%incr]
  | C_TEST_COMPILE_CONTRACT   -> [%incr]
  | C_TEST_TO_CONTRACT        -> [%incr]
  | C_TEST_ORIGINATE_FROM_FILE -> [%incr]
  | C_TEST_GET_STORAGE_OF_ADDRESS -> [%incr]
  | C_TEST_EXTERNAL_CALL_TO_ADDRESS -> [%incr]
  | C_TEST_EXTERNAL_CALL_TO_ADDRESS_EXN -> [%incr]
  | C_TEST_TO_ENTRYPOINT        -> [%incr]
  | C_POLYMORPHIC_ADD         -> [%incr]
  | C_BIG_MAP_IDENTIFIER -> [%incr]
  | C_NEVER                   -> [%incr]
  | C_TEST_MUTATE_COUNT       -> [%incr]
  | C_TEST_MUTATE_VALUE       -> [%incr]
  | C_TEST_MUTATION_TEST      -> [%incr]
  | C_TEST_MUTATION_TEST_ALL  -> [%incr]
  | C_TEST_BOOTSTRAP_CONTRACT -> [%incr]
  | C_TEST_NTH_BOOTSTRAP_CONTRACT -> [%incr]
  | C_TEST_TO_TYPED_ADDRESS   -> [%incr]
  | C_TEST_NTH_BOOTSTRAP_TYPED_ADDRESS -> [%incr]
  | C_TEST_SAVE_MUTATION      -> [%incr]

let constant' a b = Int.compare (constant'_tag a) (constant'_tag b)

let literal_tag = function
  | Literal_unit        ->  1
  | Literal_int _       ->  2
  | Literal_nat _       ->  3
  | Literal_timestamp _ ->  4
  | Literal_mutez _     ->  5
  | Literal_string _    ->  6
  | Literal_bytes _     ->  7
  | Literal_address _   ->  8
  | Literal_signature _ ->  9
  | Literal_key _       -> 10
  | Literal_key_hash _  -> 11
  | Literal_chain_id _  -> 12
  | Literal_operation _ -> 13

let literal a b = Int.compare (literal_tag a) (literal_tag b)
