#![no_std]

use core::panic::PanicInfo;

#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

// #[alloc_error_handler]
// pub fn alloc_error_handler(_: core::alloc::Layout) -> ! {
//     abort()
// }


#[panic_handler]
fn panic_handler(_info: &PanicInfo) -> ! {
    loop{}
}

#[no_mangle]
pub extern "C" fn c_add_i32(a: *mut i32, b: *mut i32) -> i32 {
  let a:i32 = unsafe { *a };
  let b:i32 = unsafe { *b };
  return a + b
}


extern "C" {
  /// The entrypoint of the smart contract. This should be generated by the LIGO
  /// wasm backend.
  pub fn entrypoint(a: i32) -> i32;
}

/**  
 * The starting point of the generated wasm file.
 *
 * It loads the data from storage, calls the LIGO wasm backend generated
 * code, and stores the data once done. Currently the operations and
 * parameters are _not_ properly handled.
 *
 */
#[no_mangle]
pub extern "C" fn _start() {
  unsafe {
    let result = entrypoint(1);
  }
}
