(library
 (name memory_proto_alpha)
 (public_name tezos-memory-proto-alpha)
 (libraries
  mavryk-protocol-001-PtAtLas.protocol
  mavkit-protocol-001-PtAtLas-libs.client
  mavryk-protocol-001-PtAtLas.parameters
  mavryk-protocol-001-PtAtLas.protocol.environment
  mavkit-protocol-001-PtAtLas-libs.test-helpers))
