(library
 (name memory_proto_alpha)
 (public_name ligo.mavryk-memory-proto-alpha)
 (libraries
  mavryk-protocol-002-PtBoreas.protocol
  mavkit-protocol-002-PtBoreas-libs.client
  mavryk-protocol-002-PtBoreas.parameters
  mavryk-protocol-002-PtBoreas.protocol.environment
  mavkit-protocol-002-PtBoreas-libs.test-helpers))
