module Non_linear_rows (Row_lhs: Non_linear_rows.Row_lhs) = Non_linear_rows.Make (Row_lhs)
module Attribute = Attribute
module Named_fun = Named_fun
module Prod = Prod
module Type_app = Type_app
module Arrow = Arrow
module Mod_access = Mod_access
module Struct_assign = Struct_assign
module Instruction_call = Instruction_call
module Case = Case
module Test_clause = Test_clause
module Cond = Cond